var members = [
  {
    "id": 1,
    "name": "Liam Morley",
    "github_profile": "https://github.com/carpeliam",
    "email": "liam@carpeliam.com",
    "projectMemberships": [1]
  },
  {
    "id": 2,
    "name": "Harlan Weber",
    "github_profile": "https://github.com/whereshj",
    "email": "hweber@codeforamerica.org",
    "projectMemberships": [2]
  },
  {
    "id": 3,
    "name": "Sarah LaPlante",
    "github_profile": "https://github.com/ohnorobo",
    "email": "sar.laplante@gmail.com",
    "projectMemberships": [3]
  },
  {
    "id": 4,
    "name": "Kristen Merrill",
    "email":"snowtackle@gmail.com",
    "projectMemberships": [4]
  },
  {
    "id": 5,
    "name": "Matt Cloyd",
    "github_profile": "https://github.com/_beechnut",
    "email": "mcloyd@codeforamerica.org",
    "projectMemberships": [5]
  }
];
var projectMembers = [
  {"id": 1, "member": 1, "project": 1, "role": "Lead Developer"},
  {"id": 2, "member": 2, "project": 1, "role": "Designer"},
  {"id": 3, "member": 3, "project": 1, "role": "Developer"},
  {"id": 4, "member": 4, "project": 1, "role": "Researcher"},
  {"id": 5, "member": 5, "project": 2, "role": "Lead Developer"}
];
var projects = [
  {
    "id": 1,
    "name": "Pantry Pickup",
    "description": "Combining city data with a list of specific needs from food pantries will allow citizens to most effectively make useful and needed donations assisted by the Pantry Pick-Up App.",
    "repository": "https://github.com/codeforboston/pantry_pickup",
    "history": "https://github.com/codeforboston/pantry_pickup/contributors",
    "projectPlan": "I know it's here somewhere, but just hit OK for now.",
    "url": "http://www.pantrypickup.org",
    "status": "In Development",
    "projectMembers": [1, 2, 3, 4],
    "skillsNeeded": ["node.js", "python"],
    "screenshots": ["/images/pantry_pickup.png"],
    "pressClippings": [],
    "featured": true,
    "githubDetails": {
      "id": 8141917,
      "name": "pantry_pickup",
      "full_name": "codeforboston/pantry_pickup",
      "owner": {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
            "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
            {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
                {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
	      {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          }
        ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          36,
          0,
          0,
          4,
          0,
          0,
          3,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          8,
          0,
          0,
          0,
          0,
          15,
          0,
          0,
          0,
          11,
          0,
          0,
          7,
          0,
          0,
          0,
          0,
          0,
          5,
          0,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "Combining city data with a list of specific needs from food pantries will allow citizens to most effectively make useful and needed donations assisted by the Pantry Pick-Up App. ",
      "fork": false,
      "createdAt": "2013-02-11T16:50:02Z",
      "updatedAt": "2014-01-08T00:22:59Z",
      "pushedAt": "2013-12-04T03:20:11Z",
      "homepage": "http://www.pantrypickup.org",
      "size": 5735,
      "stargazers_count": 14,
      "watchers_count": 14,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 11,
      "open_issues_count": 24,
      "forks": 11,
      "open_issues": 24,
      "watchers": 14,
      "default_branch": "master",
      "master_branch": "master",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      }
    }
  },
  {
    "id": 2,
    "name": "MBTA Alerts",
    "description": "The bot that tweets from the MBTA Alerts RSS feed. Saving 9K @mbta_alerts Twitter followers from information blackout!",
    "repository": "https://github.com/codeforboston/mbta_alerts",
    "history": "https://github.com/codeforboston/mbta-alerts/contributors",
    "url": "http://www.twitter.com/mbta-alerts",
    "status": "Deployed",
    "projectMembers": [5],
    "skillsNeeded": ["node.js"],
    "screenshots": [],
    "pressClippings": ["http://www.metro.us/boston/news/local/2013/06/11/code-for-boston-to-revive-mbta-alerts-twitter-account/"],
    "featured": false,
    "githubDetails": {
      "id": 10541926,
      "name": "mbta-alerts",
      "full_name": "codeforboston/mbta-alerts",
      "owner":  {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
      "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
	    {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
	  {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          }
        ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          26,
          0,
          0,
          0,
          0,
          0,
          0,
          26,
          0,
          0,
          0,
          0,
          0,
          11,
          0,
          0,
          0,
          6,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "source code for @mbta_alerts bot",
      "fork": false,
      "createdAt": "2013-06-07T03:43:17Z",
      "updatedAt": "2013-12-19T16:41:09Z",
      "pushedAt": "2013-12-19T14:33:47Z",
      "homepage": "https://twitter.com/mbta_alerts",
      "size": 244,
      "stargazers_count": 10,
      "watchers_count": 10,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 3,
      "mirrorUrl": null,
      "open_issues_count": 2,
      "forks": 3,
      "open_issues": 2,
      "watchers": 10,
      "default_branch": "master",
      "network_count": 3,
      "subscribers_count": 9
    }
  },
  {
    "id": 3,
    "name": "filter-template",
    "url": "http://codeforboston.github.io/filter-template/",
    "repository": "https://github.com/codeforboston/filter-template",
    "description": "Generic \"find-a\" app for geographic datasets",
    "projectMembers": [],
    "skillsNeeded": [],
    "githubDetails": {
      "id": 13428942,
      "name": "filter-template",
      "full_name": "codeforboston/filter-template",
      "owner": {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
         "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
            {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
      ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0,
          6,
          0,
          0,
          0,
          0,
          9,
          0,
          0,
          7,
          0,
          0,
          9,
          0,
          22,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "Generic \"find-a\" app for geographic datasets",
      "fork": false,
      "createdAt": "2013-10-09T00:18:42Z",
      "updatedAt": "2013-12-31T18:29:34Z",
      "pushedAt": "2013-11-13T19:31:28Z",
      "homepage": "http://codeforboston.github.io/filter-template",
      "size": 328,
      "stargazers_count": 2,
      "watchers_count": 2,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 9,
      "open_issues_count": 10,
      "forks": 9,
      "open_issues": 10,
      "watchers": 2,
      "default_branch": "gh-pages",
      "master_branch": "gh-pages",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      }
    }
  },
  {
    "id": 4,
    "name": "Vote Cambridge",
    "description": "People of Cambridge, find your polling location.",
    "repository": "https://github.com/codeforboston/cambridge_voting_locations",
    "updatedAt": "2014-01-19T20:01:12Z",
    "url": "http://votecambridge.com/",
    "projectMembers": [],
    "skillsNeeded": [],
    "createdAt": "2014-01-19T20:01:12Z",
    "githubDetails": {
      "id": 12097612,
      "name": "cambridge_voting_locations",
      "full_name": "codeforboston/cambridge_voting_locations",
      "owner": {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
         "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          }
      ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          15,
          0,
          0,
          14,
          0,
          0,
          0,
          2,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          0,
          6,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "People of Cambridge, find your polling location.",
      "fork": false,
      "createdAt": "2013-08-14T02:00:19Z",
      "updatedAt": "2013-11-25T18:09:25Z",
      "pushedAt": "2013-11-05T00:11:19Z",
      "homepage": "http://votecambridge.com",
      "size": 6272,
      "stargazers_count": 2,
      "watchers_count": 2,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 3,
      "open_issues_count": 0,
      "forks": 3,
      "open_issues": 0,
      "watchers": 2,
      "default_branch": "master",
      "master_branch": "master",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      }
    }
  }
];
var events = [
  {
      "apiUrl": "http://codeforamerica.org/api/events/4174",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/119077982/",
      "id": 4174,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-05-28 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4178",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/122713642/",
      "id": 4178,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-06-11 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4179",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/122713682/",
      "id": 4179,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-06-18 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4177",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/119407512/",
      "id": 4177,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-06-04 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4219",
      "createdAt": "2013-11-12 14:55:06",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/165802972/",
      "id": 4219,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-03-04 19:00:00 -0500"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4167",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/112626692/",
      "id": 4167,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-04-16 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4163",
      "createdAt": "2013-03-29 08:40:15",
      "description": "<p>Our first weekly work session of April will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/111647772/",
      "id": 4163,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-04-02 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4164",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/111647902/",
      "id": 4164,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-04-09 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4165",
      "createdAt": "2013-04-12 11:16:27",
      "description": "<p>I realize this is short notice, but a colleague of mine, a MAPC planner, is doing a Field Survey with a group of volunteers tomorrow Saturday 10am-4pm in Downtown Lynn.</p> <p>We will be using a tool created by Code for America fellows, LocalData (<a href=\"http://localdata.com/\"><a href=\"http://localdata.com/\" class=\"linkified\">http://localdata.com/</a></a>), and I think Alicia, one of the fellows/founders of LocalData, will join us tomorrow too.</p> <p>The task is to walk around a specified area and use LocalData to collect information about parcels and buildings. You only need a recent smartphone (iPhone, Android, etc.) or a tablet with a data connection to use the tool (it's an HTML5 app with a node.js backend, for those who are interested in that kind of thing). Please also bring a charger, since you'll be using the phone all the time.</p> <p>The goal is to help the community identify opportunities for redevelopment and beautification. The survey allows us to use quantitative data as basis for future analyis, in addition to existing, sometimes opinionated, qualitative information.</p> <p>As agency, we're protoyping this new process of community driven local data collection, see how it goes and if we can replicate it in or make recommendations for other communities in the Metro Boston Area. If you're curious how this process works, please join us tomorrow and find out more.</p> <p>To learn more about MAPC's work in Lynn visit <a href=\"http://www.mapc.org/downtownlynn\"><a href=\"http://www.mapc.org/downtownlynn\" class=\"linkified\">http://www.mapc.org/downtownlynn</a></a>.</p> <p>I'll be driving from Somerville to Lynn, in case somebody is interested and needs a ride.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/114010812/",
      "id": 4165,
      "location": null,
      "name": "Downtown Lynn Data Walk",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-04-13 10:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4166",
      "createdAt": "2013-04-10 12:14:10",
      "description": "<p>Local culture is hard to find. Whether it's a new band or a small established crafts fair, unless you know someone involved, you're unlikely to hear about it and you'll be unable to find it. Major attractions have marketing teams to promulgate their events; local culture doesn't. Simply having a website or a Facebook event only connects those within one degree of that social network.</p> <p>Urbanite will make it possible to discover all of this local culture. Attractions will be able to post events and users will be able to discover the local culture flourishing in their very neighborhood.</p> <p>We are still in the early stages of development. We're currently building a demo/test site where we can create, edit, display, and search for events. At the same time, our current team is giving themselves a crash course in Rails, MongoDB, and the other technology we hope to use, so it's easy to jump right into the Urbanite team.</p> <p>There's a lot to be done and these extended hack sessions are where we'll do it. If you're interested in learning about Urbanite or contributing to the project, come on by.</p> <p>While you're at it, you can check out Urbanite on Github: <a href=\"https://github.com/codeforboston/urbanite\" class=\"linkified\">https://github.com/codeforboston/urbanite</a></p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/113661502/",
      "id": 4166,
      "location": null,
      "name": "Urbanite Extended Hack Session",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-04-14 15:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4168",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/112626712/",
      "id": 4168,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-04-23 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4169",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/112626732/",
      "id": 4169,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-04-30 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4170",
      "createdAt": "2013-04-07 21:29:13",
      "description": "<p>Join us this Saturday and collaborate with us to improve an app that promotes green spaces in Metro Boston:</p> <p><a href=\"https://github.com/codeforboston/bostongreenmap\" class=\"linkified\">https://github.com/codeforboston/bostongreenmap</a></p> <p>The goal of this mapping application is to help residents discover and explore green spaces and activities in their neighborhoods they didn\u2019t know about. The project was\u00a0bootstrapped\u00a0during Boston's Hack Day Challenge, a 48 hour Hackathon. We're going to help get the app ready for prime time.</p> <p>This is an opportunity for anybody interested in green spaces to\u00a0unleash their can-do spirit and turn public open space data into a\u00a0user friendly public service.</p> <p>On this Saturday we will\u2026</p> <p>\u2026 do some usability testing<br/>\u2026 write some code<br/>\u2026 tweak some designs<br/>\u2026 take and curate some photos<br/>\u2026 or do whatever it takes to make the application better</p> <p>We\u2019re preparing this version for the Metro Boston area, but if you\u2019re interested in deploying the app in your city or town, please stop by and see how you could use it in your community.</p> <p>Thanks to Continuum for sponsoring venue, infrastructure, and snacks\u00a0throughout the day.</p> <p>Venue access:</p> <p>Bus: several Bus stops are within walking distance, please see transit maps for Bus Numbers Commuter Rail: West Newton on Framingham/Worcester Line Car: I 90, Exit 16 or 17</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/113212512/",
      "id": 4170,
      "location": null,
      "name": "Earth Day Hack Day",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-05-04 10:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4171",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/114120182/",
      "id": 4171,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-05-07 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4172",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/114497672/",
      "id": 4172,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-05-14 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4173",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/118998042/",
      "id": 4173,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-05-21 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4175",
      "createdAt": "2013-05-19 12:56:58",
      "description": "<p>The <a href=\"http://spring2013bostoncivicexpo.eventbrite.com/\">Boston Civic Expo</a> is part of the celebration of the National Day of Civic Hacking here in Boston. Intended as a celebration of all the great civic innovation work being done in the area, the Expo is intended to help like-minded civic groups that may not often work together (or even be aware of each other\u2019s existence!) to meet and mingle, fostering an atmosphere of learning and collaboration.</p> <p>Featuring two hours of IGNITE-style talks from local civic innovators, academics, technologists, and community groups - including the Brigade, New Urban Mechanics, MAPC, and more - followed by an hour of topic-based breakout sessions, we hope that Expo will turbocharge the civic tech movement in Boston.</p> <p><br/>You can register at the <a href=\"http://spring2013bostoncivicexpo.eventbrite.com/\">Civic Expo Eventbrite</a>, and don't forget to check out the other NCoCH event over the weekend of June 1-2, <a href=\"http://june2013rhokboston.eventbrite.com/\">RHoK Boston</a>! We hope to see you there!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/120156102/",
      "id": 4175,
      "location": null,
      "name": "Boston Civic Expo",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-05-31 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4176",
      "createdAt": "2013-05-19 13:05:15",
      "description": "<p>The <a href=\"http://june2013rhokboston.eventbrite.com/\">RHoK Boston!</a> hackathon is part of the celebration of the National Day of Civic Hacking here in Boston.</p> <p>For those who aren't familiar with the format, <a href=\"http://www.rhok.org/\">Random Hacks of Kindness (RHoK)</a> hackathons are community-driven tech events where local stakeholders and subject matter experts bring problem statements from the local community to the event, which are then the focus of the hacking activities. We've assembled a number of great challenges to address from the US Census, EPA, and more - and we'd love you to bring your own!</p> <p>You can register at the <a href=\"http://june2013rhokboston.eventbrite.com/\">RHoK Boston! Eventbrite</a>, and don't forget to check out the other NCoCH event on May 31, <a href=\"http://spring2013bostoncivicexpo.eventbrite.com/\">the Boston Civic Expo</a>. We hope to see you there!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/120157592/",
      "id": 4176,
      "location": null,
      "name": "RHoK Boston!",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-06-01 10:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4181",
      "createdAt": "2013-04-25 17:55:58",
      "description": "<p>We'll get our monthly Demo Night events kicked off with a special RHoK edition! In addition to Brigade project teams, all participants in the June 1-2 RHoK Boston event are welcome to come and present their work to show off what you've been up to over the last month. It will be a chance to get some great feedback before submitting your app to the White House Challenge: <a href=\"http://hackforchange.org/submit\" class=\"linkified\">http://hackforchange.org/submit</a></p> <p>Hope to see you there!</p> <p>----------</p> <p>The event will be at the Cambridge Innovation Center in Kendall Square, on the FIFTH FLOOR, in the HAVANA room.</p> <p>At demo nights, Brigade teams will have the opportunity to show off the projects they're working on, celebrate successful work, and discuss blockers they're working through. We may be joined by members of the public, and may have outside guests present their own work to the Brigade community.</p> <p>There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT parking lot at Hayward St is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive, and take the elevator to the 5th floor; the Havana room is to the left. Looking forward to seeing you there!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/116202652/",
      "id": 4181,
      "location": null,
      "name": "Monthly Demo Night: RHoK Special Edition!",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-06-25 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4182",
      "createdAt": "2013-06-09 15:33:55",
      "description": "<p>Dan O' Brien from the Boston Area Research Initiative invited us to this presentation on analysis of Citizen's Connect data, seemed like it would be really interesting for the data-minded among us. I'll leave the Meetup RSVP open, but you need to go through their registration process to ensure a spot.</p> <p><b>The event is free and open to the public, but pre-registration is required. To register, click here or go to <a href=\"http://www.rsvpbook.com/BARI\"><a href=\"http://www.rsvpbook.com/BARI\" class=\"linkified\">http://www.rsvpbook.com/BARI</a></a> by Wednesday, June 12.</b></p> <p>----------</p> <p>Featuring presentations and comments by:</p> <p>Nigel Jacob and Chris Osgood, Co-Directors, the Mayor\u2019s Office of New Urban Mechanics Dan O'Brien, Research Director, Boston Area Research Initiative Eric Gordon, Director, Engagement Game Lab and Associate Professor of Visual Media Arts, Emerson College Marie St. Fleur, Director of Intergovernmental Relations for the City of Boston Sarah Williams, assistant professor at MIT\u2019s Department of Urban Studies and Director, MIT\u2019s Civic Data Design Lab Organized by the Boston Area Research Initiative (BARI), the Mayor\u2019s Office of New Urban Mechanics (MONUM) and Emerson College\u2019s Engagement Game Lab, this event will focus on cutting-edge collaborations between policymakers and researchers to explore how citizens use the City of Boston\u2019s Mayor\u2019s Hotline and other systems, such as the Citizens Connect smart phone application, for requesting city services.</p> <p><br/>The evening will consist of two panels moderated by Nigel Jacob and Chris Osgood, who co-direct MONUM. The first panel will feature brief talks by local researchers who have been studying the use of the Mayor\u2019s Hotline. Dan O\u2019Brien, BARI\u2019s research director, will explore what the database generated by the Hotline has been able to tell us about Boston\u2019s neighborhoods and their residents. Eric Gordon, who directs Emerson\u2019s Engagement Game Lab, will discuss the Hotline as an example of using modern technology to encourage greater citizen engagement in local neighborhoods. A second panel of local experts will respond to the earlier presentations in an open discussion among presenters and attendees.</p> <p>The focus of the panel will be on how researchers, practitioners, and others can build on the research to better understand neighborhoods, improve public policy, and enhance the delivery of basic services. These experts include Marie St. Fleur, director of intergovernmental relations for the City of Boston, Sarah Williams, an assistant professor at MIT\u2019s Department of Urban Studies who also directs MIT\u2019s Civic Data Design Lab, and directors of similar government hotlines in Massachusetts.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/123768652/",
      "id": 4182,
      "location": null,
      "name": "LEARNING FROM CITIZENS' CALLS: USING THE BOSTON MAYOR'S HOTLINE",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-06-26 18:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4183",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/122713742/",
      "id": 4183,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-07-02 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4184",
      "createdAt": "2013-07-03 15:31:10",
      "description": "<p>Join us for a meeting of the City of Cambridge\u2019s Telecommunications Committee at the C3 Lounge (101 Main Street, Cambridge) on Tuesday, July 9 at 7:00 PM to provide your input on the development of an open date ordinance. Discussion will range from the types of data openly available by the City, how it will be provided for public use, and the means through which the City can ensure that developers have access to data in a timely manner.</p> <p><b>Our usual space in Kathmandu will still be available: <a href=\"http://www.meetup.com/Code-for-Boston/events/122713782/\"><a href=\"http://www.meetup.com/Code-for-Boston/events/122713782/\" class=\"linkified\">http://www.meetup.com/Code-for-Boston/events/122713782/</a></a></b></p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/127809982/",
      "id": 4184,
      "location": null,
      "name": "City of Cambridge Telecommunications Committee Meeting",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-07-09 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4185",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p><b>A quick note: Many of the Brigade members will be attending the <a href=\"http://www.meetup.com/Code-for-Boston/events/127809982/\">City of Cambridge Telecommunications Committee Meeting</a> about open data tonight, so this meeting may be a bit smaller than usual. Please leave any questions in the comments. Thanks!</b></p> <p>---</p> <p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/122713782/",
      "id": 4185,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-07-09 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4186",
      "createdAt": "2013-03-29 08:42:24",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. We'll take a few minutes to go over current projects, and then have the rest of the time to hack. There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT Hayward St lot is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive. Since we only have one entry key to the building, drop a comment here when you arrive and someone will come open the door from the foyer for you. Come by to say hi and hack with us!</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/122713802/",
      "id": 4186,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-07-16 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4188",
      "createdAt": "2013-04-28 20:39:37",
      "description": "<p>For this month's Demo Night, we'll be co-hosting with the <a href=\"https://twitter.com/IxDABoston\">Boston Interaction Design Association (IxDA).</a> Let's make sure to give a big welcome from Code for Boston to our design colleagues!</p> <p>----------</p> <p>Our monthly Demo Night will be at the Cambridge Innovation Center in Kendall Square, on the FIFTH FLOOR, in the HAVANA room.</p> <p>At demo nights, Brigade teams will have the opportunity to show off the projects they're working on, celebrate successful work, and discuss blockers they're working through. We may be joined by members of the public, and may have outside guests present their own work to the Brigade community.</p> <p>There is a pay parking lot underneath the building, and limited meter parking in the area. The MIT parking lot at Hayward St is free after 5pm. The best way to get to CIC is by Red Line.</p> <p>Please make sure to check in with security when you arrive, and take the elevator to the 5th floor; the Havana room is to the left. Looking forward to seeing you there!</p> <p><b>To sign up to present a product demo, pitch a new project / request help for an existing project, or speak on another topic, fill out the submission form: <a href=\"http://bit.ly/1dBkqTS\"><a href=\"http://bit.ly/1dBkqTS\" class=\"linkified\">http://bit.ly/1dBkqTS</a></a></b></p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/116672192/",
      "id": 4188,
      "location": null,
      "name": "Monthly Demo Night + IxDA",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "allProjects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "allStories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401033820,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projectsListUrl": "https://github.com/codeforboston",
        "rss": "",
        "started_on": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2013-07-30 19:00:00 -0400"
    }
];
var press = [
  {
    "title": "Code for Boston to revive MBTA Alerts! Twitter account",
    "publicationName": "Metro | Boston",
    "publicationDate": "June 11, 2013",
    "url": "http://www.metro.us/boston/news/local/2013/06/11/code-for-boston-to-revive-mbta-alerts-twitter-account/",
    "relatedProject": "MBTA Alerts",
    "relatedProjectGithub": "https://github.com/codeforboston/mbta-alerts",
    "relatedMembers": "Matt Cloyd"
  },
  {
    "title": "Civic hackers (the good kind) help local governments",
    "publicationName": "USA Today",
    "publicationDate": "June 23, 2013",
    "url": "http://www.usatoday.com/story/money/columnist/2013/06/23/baverman-columnist-entrepreneurs-startups/2445807/",
    "relatedProject": "National Day of Civic Hacking",
    "relatedProjectGithub": "",
    "relatedMembers": "Harlan Weber"
  }
];
App.Project.FIXTURES = projects;
App.ProjectMember.FIXTURES = projectMembers;
App.Member.FIXTURES = members;
App.Event.FIXTURES = events;
