App.Adapter = DS.FixtureAdapter.extend({
  queryFixtures: function(records, query, type) {
    return records.filter(function(record) {
      for (var key in query) {
        if (record[key] !== query[key]) {
          return false;
        }
      }
      return true;
    });
  }
});

App.Store = DS.Store.extend({
  adapter: App.Adapter
});


var members = [
  {
    "id": 1,
    "name": "Liam Morley",
    "github_profile": "https://github.com/carpeliam",
    "email": "liam@carpeliam.com",
    "projectMemberships": [1]
  },
  {
    "id": 2,
    "name": "Harlan Weber",
    "github_profile": "https://github.com/whereshj",
    "email": "hweber@codeforamerica.org",
    "projectMemberships": [2]
  },
  {
    "id": 3,
    "name": "Sarah LaPlante",
    "github_profile": "https://github.com/ohnorobo",
    "email": "sar.laplante@gmail.com",
    "projectMemberships": [3]
  },
  {
    "id": 4,
    "name": "Kristen Merrill",
    "email":"snowtackle@gmail.com",
    "projectMemberships": [4]
  },
  {
    "id": 5,
    "name": "Matt Cloyd",
    "github_profile": "https://github.com/_beechnut",
    "email": "mcloyd@codeforamerica.org",
    "projectMemberships": [5]
  }
];
var projectMembers = [
  {"id": 1, "member": 1, "project": 1, "role": "Lead Developer"},
  {"id": 2, "member": 2, "project": 1, "role": "Designer"},
  {"id": 3, "member": 3, "project": 1, "role": "Developer"},
  {"id": 4, "member": 4, "project": 1, "role": "Researcher"},
  {"id": 5, "member": 5, "project": 2, "role": "Lead Developer"}
];
var projects = [
  {
    "id": 1,
    "name": "Pantry Pickup",
    "description": "Combining city data with a list of specific needs from food pantries will allow citizens to most effectively make useful and needed donations assisted by the Pantry Pick-Up App.",
    "codeUrl": "https://github.com/codeforboston/pantry_pickup",
    "history": "https://github.com/codeforboston/pantry_pickup/contributors",
    "projectPlan": "I know it's here somewhere, but just hit OK for now.",
    "linkUrl": "http://www.pantrypickup.org",
    "status": "In Development",
    "projectMembers": [1, 2, 3, 4],
    "skillsNeeded": ["node.js", "python"],
    "screenshots": ["/images/pantry_pickup.png"],
    "pressClippings": [],
    "featured": true,
    "githubDetails": {
      "id": 8141917,
      "name": "pantry_pickup",
      "full_name": "codeforboston/pantry_pickup",
      "owner": {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
            "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
            {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
                {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
	      {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          }
        ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          36,
          0,
          0,
          4,
          0,
          0,
          3,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          8,
          0,
          0,
          0,
          0,
          15,
          0,
          0,
          0,
          11,
          0,
          0,
          7,
          0,
          0,
          0,
          0,
          0,
          5,
          0,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "Combining city data with a list of specific needs from food pantries will allow citizens to most effectively make useful and needed donations assisted by the Pantry Pick-Up App. ",
      "fork": false,
      "created_at": "2013-02-11T16:50:02Z",
      "updated_at": "2014-01-08T00:22:59Z",
      "pushed_at": "2013-12-04T03:20:11Z",
      "homepage": "http://www.pantrypickup.org",
      "size": 5735,
      "stargazers_count": 14,
      "watchers_count": 14,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 11,
      "open_issues_count": 24,
      "forks": 11,
      "open_issues": 24,
      "watchers": 14,
      "default_branch": "master",
      "master_branch": "master",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      }
    }
  },
  {
    "id": 2,
    "name": "MBTA Alerts",
    "description": "The bot that tweets from the MBTA Alerts RSS feed. Saving 9K @mbta_alerts Twitter followers from information blackout!",
    "codeUrl": "https://github.com/codeforboston/mbta_alerts",
    "history": "https://github.com/codeforboston/mbta-alerts/contributors",
    "linkUrl": "http://www.twitter.com/mbta-alerts",
    "status": "Deployed",
    "projectMembers": [5],
    "skillsNeeded": ["node.js"],
    "screenshots": [],
    "pressClippings": ["http://www.metro.us/boston/news/local/2013/06/11/code-for-boston-to-revive-mbta-alerts-twitter-account/"],
    "featured": false,
    "githubDetails": {
      "id": 10541926,
      "name": "mbta-alerts",
      "full_name": "codeforboston/mbta-alerts",
      "owner":  {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
      "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "linkUrl": "https://api.github.com/users/haileypate"
          },
	    {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
	  {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          }
        ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          26,
          0,
          0,
          0,
          0,
          0,
          0,
          26,
          0,
          0,
          0,
          0,
          0,
          11,
          0,
          0,
          0,
          6,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "source code for @mbta_alerts bot",
      "fork": false,
      "created_at": "2013-06-07T03:43:17Z",
      "updated_at": "2013-12-19T16:41:09Z",
      "pushed_at": "2013-12-19T14:33:47Z",
      "homepage": "https://twitter.com/mbta_alerts",
      "size": 244,
      "stargazers_count": 10,
      "watchers_count": 10,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 3,
      "mirrorUrl": null,
      "open_issues_count": 2,
      "forks": 3,
      "open_issues": 2,
      "watchers": 10,
      "default_branch": "master",
      "network_count": 3,
      "subscribers_count": 9
    }
  },
  {
    "id": 3,
    "name": "filter-template",
    "linkUrl": "http://codeforboston.github.io/filter-template/",
    "codeUrl": "https://github.com/codeforboston/filter-template",
    "description": "Generic \"find-a\" app for geographic datasets",
    "projectMembers": [],
    "skillsNeeded": [],
    "githubDetails": {
      "id": 13428942,
      "name": "filter-template",
      "full_name": "codeforboston/filter-template",
      "owner": {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
         "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
            {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          },
      ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0,
          6,
          0,
          0,
          0,
          0,
          9,
          0,
          0,
          7,
          0,
          0,
          9,
          0,
          22,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "Generic \"find-a\" app for geographic datasets",
      "fork": false,
      "created_at": "2013-10-09T00:18:42Z",
      "updated_at": "2013-12-31T18:29:34Z",
      "pushed_at": "2013-11-13T19:31:28Z",
      "homepage": "http://codeforboston.github.io/filter-template",
      "size": 328,
      "stargazers_count": 2,
      "watchers_count": 2,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 9,
      "open_issues_count": 10,
      "forks": 9,
      "open_issues": 10,
      "watchers": 2,
      "default_branch": "gh-pages",
      "master_branch": "gh-pages",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      }
    }
  },
  {
    "id": 4,
    "name": "Vote Cambridge",
    "description": "People of Cambridge, find your polling location.",
    "codeUrl": "https://github.com/codeforboston/cambridge_voting_locations",
    "updatedAt": "2014-01-19T20:01:12Z",
    "linkUrl": "http://votecambridge.com/",
    "projectMembers": [],
    "skillsNeeded": [],
    "createdAt": "2014-01-19T20:01:12Z",
    "githubDetails": {
      "id": 12097612,
      "name": "cambridge_voting_locations",
      "full_name": "codeforboston/cambridge_voting_locations",
      "owner": {
        "login": "codeforboston",
        "id": 2533182,
        "gravatar_id": "813975f07f37957ba1c45c726270b5dd",
        "type": "Organization",
        "site_admin": false
      },
         "contributors": [
          {
            "avatarUrl": "https://avatars.githubusercontent.com/u/1103232?",
            "contributions": 4,
            "htmlUrl": "https://github.com/haileypate",
            "login": "haileypate",
            "owner": false,
            "url": "https://api.github.com/users/haileypate"
          }
      ],
"participation": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          15,
          0,
          0,
          14,
          0,
          0,
          0,
          2,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          0,
          6,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          0,
          1
        ],
      "private": false,
      "description": "People of Cambridge, find your polling location.",
      "fork": false,
      "created_at": "2013-08-14T02:00:19Z",
      "updated_at": "2013-11-25T18:09:25Z",
      "pushed_at": "2013-11-05T00:11:19Z",
      "homepage": "http://votecambridge.com",
      "size": 6272,
      "stargazers_count": 2,
      "watchers_count": 2,
      "language": "JavaScript",
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "forks_count": 3,
      "open_issues_count": 0,
      "forks": 3,
      "open_issues": 0,
      "watchers": 2,
      "default_branch": "master",
      "master_branch": "master",
      "permissions": {
        "admin": false,
        "push": false,
        "pull": true
      }
    }
  }
];
var events = [
  {
      "apiUrl": "http://codeforamerica.org/api/events/4256",
      "createdAt": "2014-03-18 09:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyspbgb/",
      "id": 4256,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-11-04 19:00:00 -0500"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/5128",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>For this week's civic hack night, we'll be trying out a new venue at Workbar in Cambridge. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for Workbar is Central. For those who drive, there are pay parking lots on\u00a0Franklin and Pearl Streets; Bishop Allen &amp; Essex Street; Bishop Allen &amp; Norfolk Street; and on Green Street. There is also metered street parking on Bishop Allen, Mass Ave, and other surrounding streets.</p> <p><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p>During the event, <a href=\"https://codeforboston.hackpad.com/27-May-2014-hacknights-mzLMUBIy3Dj\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/181530362/",
      "id": 5128,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-05-27 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/5129",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p>During the event, <a href=\"https://codeforboston.hackpad.com/3-June-2014-hacknights-ZUIEAZWd59P\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/181530152/",
      "id": 5129,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-06-03 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4235",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysjbnb/",
      "id": 4235,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-06-10 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4236",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysjbwb/",
      "id": 4236,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-06-17 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4237",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysjbgc/",
      "id": 4237,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-06-24 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4238",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyskbcb/",
      "id": 4238,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-07-01 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4239",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyskblb/",
      "id": 4239,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-07-08 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4240",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyskbtb/",
      "id": 4240,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-07-15 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4241",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyskbdc/",
      "id": 4241,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-07-22 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4242",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyskbmc/",
      "id": 4242,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-07-29 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4243",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyslbhb/",
      "id": 4243,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-08-05 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4244",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyslbqb/",
      "id": 4244,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-08-12 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4245",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyslbzb/",
      "id": 4245,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-08-19 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4246",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjyslbjc/",
      "id": 4246,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-08-26 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4247",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysmbdb/",
      "id": 4247,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-09-02 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4248",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysmbmb/",
      "id": 4248,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-09-09 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4249",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysmbvb/",
      "id": 4249,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-09-16 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4250",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysmbfc/",
      "id": 4250,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-09-23 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4251",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysmbnc/",
      "id": 4251,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-09-30 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4252",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysnbkb/",
      "id": 4252,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-10-07 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4253",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysnbsb/",
      "id": 4253,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-10-14 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4254",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysnbcc/",
      "id": 4254,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-10-21 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4255",
      "createdAt": "2014-03-18 10:38:35",
      "description": "<p>Our weekly work session will be at the Cambridge Innovation Center in Kendall Square, on the FOURTH FLOOR, in the KATHMANDU room. These Hack Nights are our time to meet in person to work on and discuss civic tech projects. Come by to say hi and hack with us!</p> <p><b>Transportation</b><br/>The Red Line stop for CIC is Kendall. For those who drive, there is a pay parking lot underneath the building, and limited meter parking in the area. Additionally, <a href=\"http://goo.gl/maps/3WsJV\">the MIT Hayward St lot</a> is free after 5pm. <i>Please make sure to check in with security when you arrive.</i></p> <p><br/><b>Schedule</b><br/>7:00pm - Welcoming chitchat, pizza, featured project issue<br/>7:15pm - New member orientation<br/>7:30pm - Announcements<br/>7:35pm - Project reports<br/>7:45pm - Tech talk<br/>8:00pm - Hacking!</p> <p><br/>During the event, <a href=\"https://codeforboston.hackpad.com/18-March-2014-hacknights-dUaGQsaFujn\">join our Hackpad for announcement links and collaborative note taking</a>.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/qlglcjysnblc/",
      "id": 4255,
      "location": null,
      "name": "Weekly Hack Night",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-10-28 19:00:00 -0400"
    },
    {
      "apiUrl": "http://codeforamerica.org/api/events/4257",
      "createdAt": "2014-03-20 20:07:33",
      "description": "<p>Hello, CityCampers!</p> <p>Although it fills us with sadness, the Code for Boston Core Team has regretfully decided that this weekend's CityCamp event will have to be <b>postponed</b> until a later date. A few different factors came together to substantially affect attendance for the event, and it seems to make sense to move the event to a date when more community members can attend. We'll keep you posted about the new date right here on this page when it becomes available.</p> <p><br/>However, this doesn't mean we're standing still! We are laser-focused on our upcoming <a href=\"http://www.meetup.com/Code-for-Boston/events/169976402/\">Random Hacks of Kindness (RHoK) Boston for the National Day of Civic Hacking</a>. Over the next few weeks at Code for Boston Civic Hack Nights, we'll be inviting guests from the community to workshop problem sets to pursue during RHoK - sort of taking some of the CityCamp goodness and spreading it out over the next month.</p> <p><br/>Again, we apologize for the inconvenience for those who have already RSVPed - thank you so much for your interest and commitment. We're looking forward to seeing you all around hack nights and at RHoK!</p> <p><br/>- Harlan, Matt, Lyre, and the rest of the Code for Boston team</p> <p><br/>---</p> <p><br/>Boston's civic tech community is evolving rapidly, and is eager to help shape how we address urban challenges in Greater Boston. Code for Boston is bringing together the civic tech community with government, nonprofit, and other public service organizations to connect, explore, and learn from one another at CityCamp.</p> <p>During the event, we will generate rich discussion, align understandings of the local problems our organizations are trying to solve, and explore how the civic tech community can be a long-term partner in these efforts.</p> <p>At our next event, the National Day of Civic Hacking (May 30 - June 1), we will develop and implement solutions to the challenges we explore during CityCamp.</p> <p>We invite you to join us for this one-day unconference to collaborate on the challenges facing our city and nation. By building new bridges within our community, we will redefine what our organizations can do together.</p>",
      "endTime": null,
      "eventUrl": "http://www.meetup.com/Code-for-Boston/events/172477722/",
      "id": 4257,
      "location": null,
      "name": "RESCHEDULED (SEE BELOW): CityCamp Boston: Redefining the possible",
      "organization": {
        "allEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/events",
        "all_projects": "http://codeforamerica.org/api/organizations/Code-for-Boston/projects",
        "all_stories": "http://codeforamerica.org/api/organizations/Code-for-Boston/stories",
        "apiUrl": "http://codeforamerica.org/api/organizations/Code-for-Boston",
        "city": "Boston, MA",
        "eventsUrl": "http://www.meetup.com/Code-for-Boston/",
        "last_updated": 1401044648,
        "latitude": 42.3584,
        "longitude": -71.0598,
        "name": "Code for Boston",
        "pastEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/pastEvents",
        "projects_listUrl": "https://github.com/codeforboston",
        "rss": "",
        "startedOn": "2014-04-30",
        "type": "Brigade",
        "upcomingEvents": "http://codeforamerica.org/api/organizations/Code-for-Boston/upcomingEvents",
        "website": "http://www.codeforboston.org"
      },
      "organization_name": "Code for Boston",
      "startTime": "2014-11-09 10:00:00 -0500"
    }
];
var press = [
  {
    "title": "Code for Boston to revive MBTA Alerts! Twitter account",
    "publicationName": "Metro | Boston",
    "publicationDate": "June 11, 2013",
    "url": "http://www.metro.us/boston/news/local/2013/06/11/code-for-boston-to-revive-mbta-alerts-twitter-account/",
    "relatedProject": "MBTA Alerts",
    "relatedProjectGithub": "https://github.com/codeforboston/mbta-alerts",
    "relatedMembers": "Matt Cloyd"
  },
  {
    "title": "Civic hackers (the good kind) help local governments",
    "publicationName": "USA Today",
    "publicationDate": "June 23, 2013",
    "url": "http://www.usatoday.com/story/money/columnist/2013/06/23/baverman-columnist-entrepreneurs-startups/2445807/",
    "relatedProject": "National Day of Civic Hacking",
    "relatedProjectGithub": "",
    "relatedMembers": "Harlan Weber"
  }
];
App.Project.FIXTURES = projects;
App.ProjectMember.FIXTURES = projectMembers;
App.Member.FIXTURES = members;
App.Event.FIXTURES = events;
